SocialGouv/mon-psy-sante

.github/workflows/release.yml, .releaserc.yml, package.json
Il y avait un petit souci sur la config de semantic-release pour les branches `main`
=> chore(ci): fix release

.github/workflows/production.yml
override prod workflow variables to match prod url
=> fix(ci): fix prod url

.github/workflows/production.yml, .github/workflows/review.yml, Dockerfile
Add a `PRODUCTION` docker build arg that create a different `robots.txt`
=> fix(docker): dynamic robots.txt

cypress/integration/faq.spec.js, src/pages/faq.tsx, src/pages/medecins.tsx, src/pages/patients.tsx, src/pages/psychologues.tsx, src/services/faq/faq.ts
Fix: https://github.com/SocialGouv/mon-psy-sante/projects/1#card-78077795
=> feat(faq): add tab to FAQ page

.socialgouv/config.json
increase available ressources and probes timeout
=> fix: increase ressources

package.json, public/css/style.css, src/components/Directory/SearchBar.tsx, src/services/frontend/geo.api.ts, yarn.lock
Fix https://github.com/SocialGouv/mon-psy-sante/issues/143
=> fix(city input): use react autocomplete instead of SearchableSelect which does not work on safari

package.json, src/components/Admin/AdminSearchField.tsx, src/components/Admin/PsychologistForm.tsx, src/components/Admin/PsychologistsForInstructors.tsx, src/components/Contact/Form.tsx, src/components/Contact/index.tsx, src/components/Directory/SearchBar.tsx, src/components/Directory/index.tsx, src/components/Nav.tsx, src/pages/faq.tsx, yarn.lock
- downgrade dsfr and react-dsfr
- add some `ts-ignore` where react-dsfr defitnitions are outdated
- fix navigation issue in Header/Nav
=> fix: downgrade dsfr

src/components/Admin/Header.tsx, src/pages/administration-annuaire/psychologists/[id].tsx
(toujours pour m'entrainer et aussi parce que je dois prendre un train dans pas longtemps !)
=> feat(style): improve breadcrumb

.kube-workflow/prod/values.yaml
Add redirections for legacy domains
=> fix(k8s): add redirectFrom for legacy domains

src/pages/api/auth/[...nextauth].ts, src/pages/auth/signin.tsx
Pas d'urgence là dessus mais ça me permet de continuer à m'entrainer ! (en l'occurrence next-auth et design system de l'état que je n'avais jamais utilisé)
=> feat: improve login page for admin

.kube-workflow/prod/values.yaml
=> fix(k8s): add www prefixes for additional domains

.kube-workflow/prod/templates/reportingExpertWeekly.yaml, src/cron/cronUtils.ts, src/cron/launch.ts, src/cron/reportingExpertWeekly.ts, src/cron/sendReporting.ts, src/services/demarchesSimplifiees/buildRequest.ts, src/types/psychologist.d.ts
=> feat(cron): reporting expert weekly

.kube-workflow/prod/templates/reportingDossierEligible.yaml, src/cron/launch.ts, src/cron/reportingDossierEligible.ts, src/services/demarchesSimplifiees/buildRequest.ts
~~WIP (todo envoyer par mail comme pour les autres dès que c'est validé)~~
=> feat(cron): export dossier eligible

public/images/Video-Medecin.mp4.vtt, src/pages/medecins.tsx
=> feat: video medecin

src/__tests__/psychologists-update.spec.ts, src/services/__tests__/format-psychologist.spec.ts, src/services/format-psychologists.ts
Autoriser le fait de rendre le site web vide via l'admin (pour "supprimer" un site web)
@carolineBda Ah, d'ailleurs j'ai fait ce fix en TDD, ça tombe en même temps que ton message (enfin je crois que c'est ça : j'ai codé le test, le test marchait pas, j'ai codé le fix)
=> fix(admin): allow empty website

src/__tests__/psychologists-update.spec.ts, src/components/Admin/PsychologistForm.tsx, src/components/Directory/index.tsx, src/db/migrations/20221003082106-change-public-values.js, src/pages/api/admin/psychologists/[id].ts, src/services/__tests__/ds-parse-psychologists.spec.ts, src/services/__tests__/psychologists.spec.ts, src/services/demarchesSimplifiees/parse-psychologists.ts, src/services/psychologists.ts, src/types/enums/public.ts
Vu avec l'équipe, normalement c'est bon @carolineBda !
=> feat: new filters for adultes, ado, enfants

src/components/Breadcrumb.tsx, src/components/Directory/Footer.tsx, src/components/Directory/SearchBar.tsx, src/components/Directory/index.tsx, src/pages/accessibilite.tsx, src/pages/contact.tsx, src/pages/faq.tsx, src/pages/index.tsx, src/pages/medecins.tsx, src/pages/mentions-legales.tsx, src/pages/politique-de-confidentialite.tsx, src/pages/psychologues.tsx, src/pages/stats.tsx, src/services/__tests__/psychologists.spec.ts, src/services/matomo.ts, src/services/psychologists.ts, src/styles/style.css, src/types/enums/public.ts
Derniers retour suite au redesign + simplification du filtre pour le publique + Ajout d'un fil d'ariane
=> feat(annuaire): text changes + simplify public filter

.babelrc, .github/workflows/ci.yml, package.json, src/components/Directory/PsychologistsMap.tsx, yarn.lock
fix: [MON-PSY-SANTE-1M](https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/42409/?project=61&query=is%3Aunresolved)
=> fix: nullish-coalescing issue on old browser

src/__tests__/cron/reportingTraitementErrone.spec.ts, src/cron/reportingTraitementErrone.ts
Rapport avec Dossiers en instruction coché "notifiés éligibles" sans l’instructeur CPAM
=> feat(report): ajout d'un rapport contenant les dossiers elligible sans instructeurs CPAM

.kontinuous/env/prod/templates/importFromDS.yaml, .kontinuous/env/prod/templates/reportingDossierEligible.yaml, .kontinuous/env/prod/templates/reportingDossierRefuse.yaml, .kontinuous/env/prod/templates/reportingExpertWeekly.yaml, .kontinuous/env/prod/templates/reportingStatsByDepartment.yaml, .kontinuous/env/prod/templates/reportingTraitementErrone.yaml, .kontinuous/env/prod/templates/verifFolders.yaml, .kontinuous/values.yaml
Fix cronjobs docker image path
=> fix: cronjobs
